services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=happyparking'
      - 'MYSQL_PASSWORD=root1234!'
      - 'MYSQL_ROOT_PASSWORD=root1234!'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'

  # Spring Boot Container
  spring:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
